### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by olegispe** [william01110111/Pinecone#11]
How does one make a class? Using data structures like:
```javascript
myClass :: {
   name: ""
   myFunc :: {} -> {String} : (
      print: "Hi, " + name
   )
```
Or by using left input?
```javascript
myClass: ""
myFunc :: {myClass}.{} -> {String} : (
   print: "Hi, " + name
)
```

**Comment by william01110111** [comment]
Using left input is correct. You can  not have functions inside type definitions. Pointers are not yet implemented (or at least not exposed by the language syntax) so you can't really have proper classes. Since currently everything is pass by reference, changes you make to the objects data inside a member function will not take affect once the function returns (and even changing data in structures or tuples is not yet supported). These issues are definitely ones I will be addressing soon.
